{% set package_name = "lightpath" %}
{% set import_name = "lightpath" %}
{% set version =
load_file_regex(load_file=os.path.join(import_name, "_version.py"),
regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  entry_points:
    - lightpath = lightpath.main:entrypoint
  number: 1

requirements:
  host:
    - python >={{ python_min }}

test:
  imports:
    - lightpath

outputs:
  - name: lightpath-base
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }}
        - coloredlogs
        - happi >=1.6.0
        - ophyd
        - prettytable
      run_constrained:
        - networkx <3.3  # [py<=39]
      test:
        requires:
          - python {{ python_min }}

  - name: lightpath
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - {{ pin_subpackage('lightpath-base', max_pin='x.x.x') }}
        - python >={{ python_min }}
        - pydm
        - pyqt >=5
        - qtawesome
        - qtpy
        - typhos >=1.0.0
      test:
        imports:
          - lightpath
        requires:
          - python {{ python_min }}

about:
  home: https://github.com/pcdshub/lightpath
  license: SLAC Open License
  summary: LCLS Lightpath Module
